#!/usr/bin/env python3

# Starter for The Imaging Source cameras in ros.
# Needs Python 3
# Please refer to https://github.com/TheImagingSource/tiscamera
# Goto: http://wiki.ros.org/gscam for info.
# Install sudo apt-get install ros-kinetic-gscam

import tiscamera
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--cam_id', type=str)
parser.add_argument('--width', type=int, default=320)
parser.add_argument('--height', type=int, default=240)
parser.add_argument('--fps', type=int, default=950)

#args = parser.parse_args()
args, unknown = parser.parse_known_args()


# Open the camera. Parameters are serial number, width, height, frame rate, color and liveview.
cam = tiscamera.Camera(args.cam_id, args.width, args.height, args.fps, False, False)

# Start the live stream from the camera and also "rosrun"
cam.start_pipeline()

# Set some properties
cam.set_property("ExposureAuto", "Continuous")
cam.set_property("GainAuto", "Continuous")


input("Press Enter to end program")

# Stop the camera pipeline.
cam.stop_pipeline()

print('Program ended')
